abbr - "cd -"
abbr cl "clear"

abbr apti "apt install"
abbr apts "apt search"
abbr aptp "apt purge"

abbr sl "systemctl status"
abbr sls "systemctl start"
abbr slst "systemctl stop"
abbr slr "systemctl restart"

abbr d "docker"
abbr dc "docker-compose"
abbr ds "docker ps"
abbr dx "docker exec"

abbr g "git"
abbr ga "git add"
abbr ga. "git add ."
abbr gb "git branch"
abbr gc "git commit"
abbr gcl "git clone"
abbr gcln "git clean"
abbr gco "git checkout"
abbr gl "git pull"
abbr gp "git push"
abbr m "git commit -m"
abbr s "git status -sb"

abbr t "touch"
abbr tm "tmux"
abbr l "ls -la"

abbr abbrc "vi $HOME/.config/fish/conf.d/abbreviations.fish"
